---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-rtfm-space
  namespace: default
spec:
  secretName: grafana-rtfm-space-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "grafana.rtfm.space"
  dnsNames:
  - "grafana.rtfm.space"