- hosts: all
  become: true
  tasks:
    - name: Install NFS server
      apt:
        name: nfs-kernel-server
        state: present

    - name: Set up the NFS directory
      file:
        path: "/mnt/nfs"
        state: directory
        owner: "root"
        group: "root"
        mode: '0755'

    - name: Configure NFS exports
      blockinfile:
        path: /etc/exports
        block: |
          /mnt/nfs 192.168.1.0/24(rw,sync,no_subtree_check)

    - name: Restart NFS service
      systemd:
        name: nfs-kernel-server
        state: restarted
