---
# Ansible Configuration Variables
# https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#splitting-out-vars

k3s_version: v1.29.3+k3s1

# SSH Info
ansible_ssh_user: setheth

sytemd_dir: /etc/systemd/system

# K3s

# What interface to use for flannel networking
flannel_iface: eth0

# Password used for masters to talk to each other
k3s_token: "read the fucking manual"


# Extra Server Args
  # --disable servieclb (We will be using metallb instead)
  # --disable traefik (we will do this with helm later on)
extra_server_args: "--disable servicelb --disable traefik"

# Extra Agent Args
  #--kubelet-arg node-status-update-frequency=5s (The standard update time is 5m, this reduces it to 5s to make lab more zippy.)
extra_agent_args: "--kubelet-arg node-status-update-frequency=5s"

kube_vip_tag_version: "v0.4.2"

metal_lb_tag_version: "v0.12.1"

# This is the range of IPs metallb will assign to services to make them acessible on the lan
metal_lb_ip_range: "192.168.1.60-192.168.1.80"